## Dovecot CE FTS Drivers

Dovecot CE contains these FTS indexing drivers:

| Name | Description |
| ---- | ----------- |
| [[plugin,fts_solr]] | Interface to [Apache Solr](https://solr.apache.org/); stores data remotely. |
| [[plugin,fts_flatcurve]] | [Xapian](https://xapian.org/) based driver; stores data locally. |

There are also 3rd party provided FTS plugins:

| Name | Description |
| ---- | ----------- |
| fts-xapian | https://github.com/grosjo/fts-xapian |

If you want your plugin here, please open pull request to [dovecot/documentation](https://github.com/dovecot/documentation/pulls/new) repository.
