version: 2
updates:
  # Checks for dependency updates for documentation (VitePress)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
  # Checks for dependency updates in github actions workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
