<!-- @include: ./global-options.inc -->

**-f** *formatter*
:   Specifies the *formatter* for formatting the output. Supported
    formatters are:

    **flow**
    :    prints each line with *key*<!-- -->**=**<!-- -->*value* pairs.

    **pager**
    :    prints each *key*: *value* pair on its own line and separates
         records with form feed character (**^L**).

    **tab**
    :    prints a table header followed by tab separated value lines.

    **table**
    :    prints a table header followed by adjusted value lines.
